{% set name = "autoregistry" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autoregistry-{{ version }}.tar.gz
  sha256: c74147a6492184a9b03a02f16f90bd080eb62d174dec2a9e79e3fd10bbef818f

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.1
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - autoregistry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BrianPugh/autoregistry
  summary: Automatic registry design-pattern for mapping names to functionality.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
